#!/usr/bin/env bash
if [[ "$USER" != 'root' ]]; then
  echo "Este Script Solo Funciona Para Usuarios root"
  exit
fi
function verificar(){
apt-get install systemd -y > /dev/null 2>&1
if [ -f /bin/badvpn ]; then
iniciar
exit
else
instalar
fi
}
function instalar(){
echo "#!/bin/bash
if [ "'$1'" == start ]; then
badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 > /dev/null & echo 'Badvpn ejecutandose en puerto 7300'
fi
if [ "'$1'" == stop ]; then
badvpnpid="'$(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
kill -9 "'"$badvpnpid" >/dev/null 2>/dev/null
kill $badvpnpid > /dev/null 2> /dev/null
kill "$badvpnpid" > /dev/null 2>/dev/null''
kill $(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
killall badvpn-udpgw
fi" > /bin/badvpn
cp /bin/badvpn /bin/badvpn2
sed -i "s/7300/7200/g" /bin/badvpn2
chmod 777 /bin/badvpn
chmod 777 /bin/badvpn2
echo -e "\033[1;31m           Instalador Badvpn\n\033[1;37mInstalando badvpn...\033[0m"
apt-get update >/dev/null 2>/dev/null
apt-get install -y gcc >/dev/null 2>/dev/null
apt-get install -y make >/dev/null 2>/dev/null
apt-get install -y g++ >/dev/null 2>/dev/null
apt-get install -y openssl >/dev/null 2>/dev/null
apt-get install -y build-essential >/dev/null 2>/dev/null
apt-get install -y cmake >/dev/null 2>/dev/null
echo -e "\033[1;37mDescargando Badvpn";
cd
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -o /dev/null
#wget https://www.dropbox.com/s/bc5crnb77ban51i/badvpn-1.999.128.tar.bz2 -o /dev/null
echo -e "Descomprimiendo Badvpn"
tar -xf badvpn-1.999.128.tar.bz2
echo -e "Iniciando configuraciones"
mkdir /etc/badvpn-install
cd /etc/badvpn-install
cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 >/dev/null 2>/dev/null
echo -e "Compilando badvpn\033[0m"
make install
clear
echo -e "\033[1;32m             Instalacion completada\033[0m"
echo -e "\033[1;37mComandos:\n\033[1;31mbadvpn start\033[1;37m Para ejecutar badvpn"
echo -e "\033[1;31mbadvpn stop \033[1;37m Para detener badvpn\033[0m"
rm -rf /etc/badvpn-install
cd ; rm -rf badvpn-1.999.128/ badvpn-1.999.128.tar.bz2 >/dev/null 2>/dev/null
iniciar
rclocale="
badvpn start
badvpn2 start
exit 0
"
echo "$rclocale" > /etc/rc.local
rm $0
}
function iniciar(){
if [ -f /etc/code/badvpn.sh ];
then
echo "#!/usr/bin/env bash
badvpn start" > /etc/code/badvpn.sh
echo "#!/usr/bin/env bash
badvpn2 start" > /etc/code/badvpn.sh
else
mkdir /etc/code
echo "#!/usr/bin/env bash
badvpn start" > /etc/code/badvpn.sh
echo "#!/usr/bin/env bash
badvpn2 start" > /etc/code/badvpn.sh
fi
echo "[Unit]
Description=SERVICIO BADVPN SOPORTE DE VIDEOLLAMADAS(UDP)
After=network.target

[Service]
Type=forking
ExecStart=/etc/code/badvpn.sh
User=root
Restart=on-failure
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/badvpn.service
cp /etc/systemd/system/badvpn.service /etc/systemd/system/badvpn2.service
sed -i "s/7300/7200/g" /etc/systemd/system/badvpn2.service
chmod 777 /etc/code/badvpn.sh
chmod 777 /etc/code/badvpn2.sh
chmod 777 /etc/systemd/system/badvpn.service
chmod 777 /etc/systemd/system/badvpn2.service
systemctl daemon-reload > /dev/null 2>&1
systemctl enable badvpn.service > /dev/null 2>&1
systemctl start badvpn.service > /dev/null 2>&1
systemctl enable badvpn2.service > /dev/null 2>&1
systemctl start badvpn2.service > /dev/null 2>&1
echo "badvpn ejecutandose en puerto 7200"
echo "badvpn ejecutandose en puerto 7300"
}
verificar
