#!/usr/bin/env bash

function verificar(){
if [ -f /bin/badvpn ]; then
iniciar
exit
else
instalar
fi
}
function instalar(){
echo "#!/bin/bash
if [ "'$1'" == start ]
then
badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 > /dev/null &
echo 'Badvpn ejecutandose en puerto 7300'
fi
if [ "'$1'" == stop ]
then
badvpnpid="'$(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
kill -9 "'"$badvpnpid" >/dev/null 2>/dev/null
kill $badvpnpid > /dev/null 2> /dev/null
kill "$badvpnpid" > /dev/null 2>/dev/null''
kill $(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
killall badvpn-udpgw
fi" > /bin/badvpn
chmod +x /bin/badvpn
echo -e "\033[1;31m           Instalador Badvpn\n\033[1;37mInstalando badvpn...\033[0m"
apt-get update >/dev/null 2>/dev/null
apt-get install -y gcc >/dev/null 2>/dev/null
apt-get install -y make >/dev/null 2>/dev/null
apt-get install -y g++ >/dev/null 2>/dev/null
apt-get install -y openssl >/dev/null 2>/dev/null
apt-get install -y build-essential >/dev/null 2>/dev/null
apt-get install -y cmake >/dev/null 2>/dev/null
echo -e "\033[1;37mDescargando Badvpn"; cd
#wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -o /dev/null
wget https://www.dropbox.com/s/bc5crnb77ban51i/badvpn-1.999.128.tar.bz2 -o /dev/null
echo -e "Descomprimiendo Badvpn"
tar -xf badvpn-1.999.128.tar.bz2
echo -e "Iniciando configuraciones"
mkdir /etc/badvpn-install
cd /etc/badvpn-install
cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 >/dev/null 2>/dev/null
echo -e "Compilando badvpn\033[0m"
make install
clear
echo -e "\033[1;32m             Instalacion completada\033[0m"
echo -e "\033[1;37mComandos:\n\033[1;31mbadvpn start\033[1;37m Para ejecutar badvpn"
echo -e "\033[1;31mbadvpn stop \033[1;37m Para detener badvpn\033[0m"
rm -rf /etc/badvpn-install
cd ; rm -rf badvpn-1.999.128/ badvpn-1.999.128.tar.bz2 >/dev/null 2>/dev/null
iniciar
rclocale="
badvpn start
exit 0
"
echo "$rclocale" > /etc/rc.local
rm $0
}
function iniciar(){
mkdir /etc/code /dev/null 2>&1
echo "#!/usr/bin/env bash
badvpn start" > /etc/code/badvpn.sh
echo "[Unit]
Description=SERVICIO BADVPN SOPRTE DE VIDEOLLAMADAS(UDP)

[Service]
Type=forking
ExecStart=/etc/code/badvpn.sh
User=root
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/badvpn.service

chmod +x /etc/code/badvpn.sh
chmod +x /etc/systemd/system/badvpn.service
systemctl daemon-reload > /dev/null 2>&1
systemctl start badvpn.service > /dev/null 2>&1
echo ""badvpn ejecutandose en puerto 7300
}
verificar
