#!/usr/bin/env bash

function verificar(){
if [ -f /usr/local/bin/badvpn-udpgw ]; then
echo -e "\033[1;32mBadvpn ya esta instalado\033[0m";
iniciar;
exit
else
instalar;
iniciar;
fi
if [ -f /usr/bin/badvpn-udpgw ]; then
echo -e "\033[1;32mBadvpn ya esta instalado\033[0m";
iniciar;
exit
instalar;
iniciar;
fi
}
function instalar(){
echo "#!/bin/bash
if [ "'$1'" == start ]
then
badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 > /dev/null &
echo 'Badvpn ejecutandose en puerto 7300'
fi
if [ "'$1'" == stop ]
then
badvpnpid="'$(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
kill -9 "'"$badvpnpid" >/dev/null 2>/dev/null
kill $badvpnpid > /dev/null 2> /dev/null
kill "$badvpnpid" > /dev/null 2>/dev/null''
kill $(ps x |grep badvpn |grep -v grep |awk '"{'"'print $1'"'})
killall badvpn-udpgw
fi" > /bin/badvpn
chmod +x /bin/badvpn
echo -e "\033[1;31m           Instalador Badvpn\n\033[1;37mInstalando badvpn...\033[0m"
apt-get update >/dev/null 2>/dev/null
apt-get install -y gcc >/dev/null 2>/dev/null
apt-get install -y make >/dev/null 2>/dev/null
apt-get install -y g++ >/dev/null 2>/dev/null
apt-get install -y openssl >/dev/null 2>/dev/null
apt-get install -y build-essential >/dev/null 2>/dev/null
apt-get install -y cmake >/dev/null 2>/dev/null
echo -e "\033[1;37mDescargando Badvpn"; cd
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2 -o /dev/null
echo -e "Descomprimiendo Badvpn"
tar -xf badvpn-1.999.128.tar.bz2
echo -e "Iniciando configuraciones"
mkdir /etc/badvpn-install
cd /etc/badvpn-install
cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1 >/dev/null 2>/dev/null
echo -e "Compilando badvpn\033[0m"
make install
clear
echo -e "\033[1;32m             Instalacion completada\033[0m"
echo -e "\033[1;37mComandos:\n\033[1;31mbadvpn start\033[1;37m Para ejecutar badvpn"
echo -e "\033[1;31mbadvpn stop \033[1;37m Para detener badvpn\033[0m"
rm -rf /etc/badvpn-install
cd ; rm -rf badvpn.sh badvpn-1.999.128/ badvpn-1.999.128.tar.bz2 >/dev/null 2>/dev/null

rclocale="
badvpn start
exit 0
"
echo "$rclocale" > /etc/rc.local
badvpn stop
badvpn start
}
function iniciar(){
badvpn stop
badvpn start
}
