#!/usr/bin/env bash
sudo su
rm -f /var/lib/dpkg/lock
dpkg --configure -a
service ssh restart
apt purge dropbear-bin -y
apt purge dropbear -y
apt remove dropbear-bin -y
apt remove dropbear -y
apt update -y
apt install dropbear-bin -y
apt install dropbear -y
cat > /etc/default/dropbear<<-EOF
#disabled because OpenSSH is installed
# change to NO_START=0 to enable Dropbear
NO_START=0
    
# the TCP port that Dropbear listens on
DROPBEAR_PORT=666

# any additional arguments for Dropbear
DROPBEAR_EXTRA_ARGS=""

# specify an optional banner file containing a message to be
# sent to clients before they connect, such as /etc/issue.net
DROPBEAR_BANNER="/etc/issue.net"

# RSA hostkey file (default: /etc/dropbear/dropbear_rsa_host_key)
#DROPBEAR_RSAKEY="/etc/dropbear/dropbear_rsa_host_key"

# DSS hostkey file (default: /etc/dropbear/dropbear_dss_host_key)
#DROPBEAR_DSSKEY="/etc/dropbear/dropbear_dss_host_key"

# Receive window size - this is a tradeoff between memory and
# network performance
DROPBEAR_RECEIVE_WINDOW=65536
EOF
service dropbear restart

apt-get install apache2 -y
sed -i 's/80/81/g' "/etc/apache2/ports.conf"
sed -i 's/443/8181/g' "/etc/apache2/ports.conf"
service apache2 restart
apt-get install sslh -y
echo 'RUN=yes
DAEMON="/usr/sbin/sslh"
DAEMON_OPTS="--user sslh --listen 167.71.81.122:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:107 -http 127.0.0.1:80 --pidfile /var/run/sslh/sslh.pid"
' > /etc/default/sslh
service sslh restart

echo "DROPBEAR INSTALADO EN PUERTO 666"
rm $0
