#!/usr/bin/env bash
sudo su
apt-get update -y;apt-get install squid -y;apt-get install apache2-utils -y;echo 'http_port 80
http_port 3128
http_port 8080
http_access allow all
cache_dir ufs /var/spool/squid 2048 16 256
visible_hostname COD3RR0R
maximum_object_size 16 MB
' > /etc/squid/squid.conf;service squid restart
