#!/usr/bin/env bash
echo "instalando stunnel espera un momento"
/etc/init.d/stunnel4 stop > /dev/null 2>&1
rm /etc/ssl/certs/stunnel.pem > /dev/null 2>&1
apt purge stunnel -y > /dev/null 2>&1
apt remove stunnel -y > /dev/null 2>&1
apt purge stunnel4 -y > /dev/null 2>&1
apt remove stunnel4 -y > /dev/null 2>&1
apt clean > /dev/null 2>&1
apt autoclean > /dev/null 2>&1
rm -r /etc/stunnel/ > /dev/null 2>&1
apt update -y > /dev/null 2>&1
apt install stunnel -y > /dev/null 2>&1
apt install stunnel4 -y > /dev/null 2>&1
#cd /etc/stunnel/
#openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 -subj "/CN=127.0.0.1/O=localhost/C=US" -keyout /etc/stunnel/stunnel.pem -out /etc/stunnel/stunnel.pem


#openssl genrsa -out stunnel.key 4096 > /dev/null 2>&1
#(echo "US" ; echo "US" ; echo "US" ; echo "US" ; echo "US" ; echo "US" ; echo "US" ) | openssl req -new -key stunnel.key -x509 -days 1000 -out stunnel.crt > /dev/null 2>&1
#cat stunnel.crt stunnel.key > stunnel.pem
#mv stunnel.pem /etc/stunnel/
wget https://github.com/egrojlive/codeerror/raw/master/stunnel.pem -O /etc/stunnel/stunnel.pem > /dev/null 2>&1
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
#echo -e "client = no\n[SSL]\ncert = /etc/stunnel/stunnel.pem\naccept = 88\nconnect = 127.0.0.1:22" > /etc/stunnel/stunnel.conf
echo '#OPENSSH
client = no
[SSL+++++]
cert = /etc/stunnel/stunnel.pem
accept = 8181
connect = 127.0.0.1:80

#OPENSSH
client = no
[SSL]
cert = /etc/stunnel/stunnel.pem
accept = 107
connect = 127.0.0.1:443

#DROPBEAR
client = no
[SSL+]
cert = /etc/stunnel/stunnel.pem
accept = 108
connect = 127.0.0.1:443

#SHADOWSOCKS-GO
client = no
[SSL++]
cert = /etc/stunnel/stunnel.pem
accept = 109
connect = 127.0.0.1:1194

#SHADOWSOCKS-LIBEV
client = no
[SSL+++]
cert = /etc/stunnel/stunnel.pem
accept = 110
connect = 127.0.0.1:8889

#SHADOWSOCKS-PYTHON
client = no
[SSL++++]
cert = /etc/stunnel/stunnel.pem
accept = 111
connect = 127.0.0.1:8890
' >> /etc/stunnel/stunnel.conf > /dev/null 2>&1
service stunnel4 restart > /dev/null 2>&1
rm $0
