#!/usr/bin/env bash
sudo su
/etc/init.d/stunnel4 stop
rm /etc/ssl/certs/stunnel.pem
apt purge stunnel -y
apt remove stunnel -y
apt purge stunnel4 -y
apt remove stunnel4 -y
apt clean
apt autoclean
rm -r /etc/stunnel/
apt update -y
apt install stunnel
apt install stunnel4 -y
#cd /etc/stunnel/
#openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -sha256 -subj "/CN=127.0.0.1/O=localhost/C=US" -keyout /etc/stunnel/stunnel.pem -out /etc/stunnel/stunnel.pem


openssl genrsa -out stunnel.key 2048 > /dev/null 2>&1
(echo "mx" ; echo "mx" ; echo "mx" ; echo "mx" ; echo "mx" ; echo "mx" ; echo "mx" ) | openssl req -new -key stunnel.key -x509 -days 1000 -out stunnel.crt > /dev/null 2>&1
cat stunnel.crt stunnel.key > stunnel.pem
mv stunnel.pem /etc/stunnel/
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
echo -e "client = no\n[SSL]\ncert = /etc/stunnel/stunnel.pem\naccept = 443\nconnect = 127.0.0.1:22" > /etc/stunnel/stunnel.conf


echo 'client = no
[SSL]
cert = /etc/stunnel/stunnel.pem
accept = 107
connect = 127.0.0.1:22

client = no
[SSL+]
cert = /etc/stunnel/stunnel.pem
accept = 108
connect = 127.0.0.1:443

client = no
[SSL++]
cert = /etc/stunnel/stunnel.pem
accept = 109
connect = 127.0.0.1:442

client = no
[shadowsocks-go]
cert = /etc/stunnel/stunnel.pem
accept = 110
connect = 127.0.0.1:8888

client = no
[shadowsocks-libev]
cert = /etc/stunnel/stunnel.pem
accept = 111
connect = 127.0.0.1:8889

client = no
[shadowsocks-py]
cert = /etc/stunnel/stunnel.pem
accept = 112
connect = 127.0.0.1:8890
' >> /etc/stunnel/stunnel.conf
service stunnel4 restart
rm $0
